nav:
  Home: /
  Writing: /archives/
  About: /about/
  #Projects: http://github.com/probberechts

#projects_url: http://github.com/probberechts

customize:
    gravatar:
        email: caopingcpu@gmail.com
    logo:
        enabled: true
        width: 50
        height: 50
        url: /images/avatar.png
        gravatar: false
    favicon:
      # eg. generate with http://realfavicongenerator.net/
      # desktop:
      #   url: /images/favicon.ico
      #   gravatar: false
      # android:
      #   url: /images/favicon-192x192.png
      #   gravator: false
      # apple:
      #   url: /images/apple-touch-icon.png
      #   gravator: false
    social_links:
        github: https://github.com/tailang
    show_all_posts: false
    post_count: 20
    highlight: rainbow

# RSS
rss: false

# Plugins
plugins:
    disqus_shortname: # Disqus Comments Shortname
    #google_analytics: UA-86660611-1 # enter the tracking ID for your Google Analytics

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
